version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: TG4YKBt2usZV
      POSTGRES_DB: verceldb
    volumes:
      - pgdata:/var/lib/postgresql/data
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "443:80"
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  pgdata: